package view;

import gate.util.GateException;

import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JTable;

import sql.SQLRead;

import logic.GateController;
import logic.Options;

public class AppWindow extends javax.swing.JFrame {

	/**
	 * Creates new form AppWindow
	 */
	public AppWindow() {
		initComponents();
		initModels();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        choosePos1 = new javax.swing.JButton();
        choosePath = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        chosenPath = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        followingWords = new javax.swing.JRadioButton();
        wholeSentence = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        run = new javax.swing.JButton();
        choosePos2 = new javax.swing.JButton();
        wordPane = new javax.swing.JScrollPane();
        basicWordPane = new javax.swing.JScrollPane();
        bigramPane = new javax.swing.JScrollPane();
        basicBigramPane = new javax.swing.JScrollPane();
        wordTfidfPane = new javax.swing.JScrollPane();
        basicWordTfidfPane = new javax.swing.JScrollPane();
        bigramTfidfPane = new javax.swing.JScrollPane();
        basicBigramTfidfPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Rodzaj bigramów");

        choosePos1.setText("Wybierz");
        choosePos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePos1ActionPerformed(evt);
            }
        });

        choosePath.setText("Wybierz");
        choosePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePathActionPerformed(evt);
            }
        });

        jLabel5.setText("Słowo 1");

        chosenPath.setText("...");

        jLabel6.setText("Słowo 2");

        jLabel4.setText("Części mowy");

        buttonGroup.add(followingWords);
        followingWords.setSelected(true);
        followingWords.setText("Kolejne słowa");

        buttonGroup.add(wholeSentence);
        wholeSentence.setText("Wszystkie słowa w zdaniu");

        jLabel1.setText("Plik/katalog wejściowy");

        run.setText("Uruchom");
        run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runActionPerformed(evt);
            }
        });

        choosePos2.setText("Wybierz");
        choosePos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePos2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(chosenPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(choosePath))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(followingWords)
                                    .addComponent(wholeSentence)))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(choosePos2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(choosePos1))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(run)))
                        .addGap(447, 447, 447)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(choosePath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chosenPath)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(followingWords)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wholeSentence)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(choosePos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(choosePos2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(run)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Opcje", jPanel1);
        jTabbedPane1.addTab("Słowa", wordPane);
        jTabbedPane1.addTab("Słowa (lemma)", basicWordPane);
        jTabbedPane1.addTab("Bigramy", bigramPane);
        jTabbedPane1.addTab("Bigramy (lemma)", basicBigramPane);
        jTabbedPane1.addTab("Słowa tf-idf", wordTfidfPane);
        jTabbedPane1.addTab("Słowa (lemma) tf-idf", basicWordTfidfPane);
        jTabbedPane1.addTab("Bigramy tf-idf", bigramTfidfPane);
        jTabbedPane1.addTab("Bigramy (lemma) tf-idf", basicBigramTfidfPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void choosePos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePos1ActionPerformed
		PosDialog dlg = new PosDialog(this, activeModel1, inactiveModel1);
		dlg.setVisible(true);
	}//GEN-LAST:event_choosePos1ActionPerformed

	private void choosePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePathActionPerformed
		JFileChooser fc = new JFileChooser();
		fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
		int ret = fc.showOpenDialog(this);
		if (ret == JFileChooser.APPROVE_OPTION) {
			String name = fc.getCurrentDirectory() + File.separator + fc.getName(fc.getSelectedFile());
			chosenPath.setText(name);
		}
	}//GEN-LAST:event_choosePathActionPerformed

	private void runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runActionPerformed
		Options options = getOptions();
		try {
			GateController gc = new GateController();
			gc.calculate(options);
			fillTables(options.getFileName());
		} catch (Exception e) {
			e.printStackTrace();
		}        

	}//GEN-LAST:event_runActionPerformed

	private void choosePos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePos2ActionPerformed
		PosDialog dlg = new PosDialog(this, activeModel2, inactiveModel2);
		dlg.setVisible(true);
	}//GEN-LAST:event_choosePos2ActionPerformed

	// gets data from SQLite file and shows it to the user
	private void fillTables(String path) {
		try {
			SQLRead read = new SQLRead(path);
			WordModel wordModel = read.getWordModel(false);
			WordModel lemmaModel = read.getWordModel(true);
			JTable wordTable = new JTable(wordModel);
			JTable lemmaTable = new JTable(lemmaModel);
			wordTable.setAutoCreateRowSorter(true);
			wordTable.setFillsViewportHeight(true);
			wordPane.setViewportView(wordTable);
			lemmaTable.setAutoCreateRowSorter(true);
			lemmaTable.setFillsViewportHeight(true);
			basicWordPane.setViewportView(lemmaTable);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private Options getOptions() {
		Options.BigramType type = getBigramType();
		ArrayList<String> paths = getPaths();
		ArrayList<String> posPane1 = getAll(activeModel1);
		ArrayList<String> posPane2 = getAll(activeModel2);
		return new Options(paths, type, posPane1, posPane2);
	}

	private ArrayList<String> getAll(DefaultListModel model) {
		ArrayList<String> list = new ArrayList<String>();
		for (int i=0; i < model.size(); i++) {
			list.add((String)model.getElementAt(i));
		}
		return list;
	}

	private Options.BigramType getBigramType() {
		if (followingWords.isSelected())
			return Options.BigramType.FOLLOWING_WORDS;
		else
			return Options.BigramType.SENTENCE;
	}

	private ArrayList<String> getPaths() {
		ArrayList<String> ret = new ArrayList<String>();
		String path = chosenPath.getText();
		File file = new File(path);

		if (file.isDirectory()) {
			for (File fileEntry : file.listFiles())
				ret.add(path + File.separator + fileEntry.getName());
		}
		else {
			ret.add(path);
		}
		return ret;
	}

	private void initModels() {
		String[] allPos = {
				"CC", "CD", "DT", "EX", "FW", "IN", "JJ", "JJR", "JJS", "JJSS", "LRB", "LS", "MD",
				"NN", "NNP", "NNPS", "NNS", "NP", "NPS",
				"PDT", "POS", "PP", "PRPR$", "PRP", "PRP$",
				"RB", "RBR", "RBS", "RP", "STAART", "SYM", "TO",
				"UH", "VBD", "VBG", "VBN", "VBP", "VB", "VBZ", "WDT",
				"WP$", "WP", "WRB"
		};
		for (String pos : allPos) {
			activeModel1.addElement(pos);
			activeModel2.addElement(pos);
		}
	}
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AppWindow().setVisible(true);
			}
		});
	}

	private DefaultListModel activeModel1 = new DefaultListModel();
	private DefaultListModel inactiveModel1 = new DefaultListModel();
	private DefaultListModel activeModel2 = new DefaultListModel();
	private DefaultListModel inactiveModel2 = new DefaultListModel();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane basicBigramPane;
    private javax.swing.JScrollPane basicBigramTfidfPane;
    private javax.swing.JScrollPane basicWordPane;
    private javax.swing.JScrollPane basicWordTfidfPane;
    private javax.swing.JScrollPane bigramPane;
    private javax.swing.JScrollPane bigramTfidfPane;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton choosePath;
    private javax.swing.JButton choosePos1;
    private javax.swing.JButton choosePos2;
    private javax.swing.JLabel chosenPath;
    private javax.swing.JRadioButton followingWords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton run;
    private javax.swing.JRadioButton wholeSentence;
    private javax.swing.JScrollPane wordPane;
    private javax.swing.JScrollPane wordTfidfPane;
    // End of variables declaration//GEN-END:variables
}
