package view;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.RowFilter.ComparisonType;
import javax.swing.table.TableRowSorter;

import model.TfidfBigramModel;

public class BigramTfidfPane extends javax.swing.JPanel {

	private final TfidfBigramModel model;
	private final JTable table;

    /**
     * Creates new form WordFilterPane
     */
    public BigramTfidfPane(JTable table) {
        initComponents();
        this.table = table;
        this.model = (TfidfBigramModel) table.getModel();
    }
    
    public JButton getFilterButton() {
    	return filterButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        document = new javax.swing.JTextField();
        word2 = new javax.swing.JTextField();
        word1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfidfFrom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfidfTo = new javax.swing.JTextField();
        filterButton = new javax.swing.JButton();

        jLabel1.setText("Słowo 1");

        jLabel2.setText("Słowo 2");

        jLabel3.setText("Dokument");

        jLabel4.setText("Tf-idf");

        jLabel5.setText("od");

        jLabel6.setText("do");

        filterButton.setText("Filtruj");
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(document)
                    .addComponent(word2)
                    .addComponent(word1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfidfFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfidfTo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 152, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(filterButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(word1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(word2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(document, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(tfidfFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfidfTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(filterButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
    	TableRowSorter<TfidfBigramModel> sorter = new TableRowSorter<TfidfBigramModel>(model);
    	table.setRowSorter(sorter);
    	
    	List<RowFilter<TfidfBigramModel,Object>> filters = new ArrayList<RowFilter<TfidfBigramModel,Object>>();
    	RowFilter<TfidfBigramModel, Object> word1Filter = null;
    	RowFilter<TfidfBigramModel, Object> word2Filter = null;
    	RowFilter<TfidfBigramModel, Object> doc = null;
    	
    	addFromToDoubleFilter(tfidfFrom, tfidfTo, filters, 3);
    	
    	RowFilter<TfidfBigramModel, Object> compoundRowFilter = null;
    	
        //If current expression doesn't parse, don't update.
        try {
            word1Filter = RowFilter.regexFilter(word1.getText(), 0);
            word2Filter = RowFilter.regexFilter(word2.getText(), 1);
            doc = RowFilter.regexFilter(document.getText(), 2);
            filters.add(word1Filter);
            filters.add(word2Filter);
            filters.add(doc);
            compoundRowFilter = RowFilter.andFilter(filters);
        } catch (java.util.regex.PatternSyntaxException e) {
            return;
        }
        
        sorter.setRowFilter(compoundRowFilter);

    }//GEN-LAST:event_filterButtonActionPerformed
    
    private void addFromToDoubleFilter(JTextField from, JTextField to, 
    		List<RowFilter<TfidfBigramModel,Object>> filters, int col) {
    	if (!from.getText().isEmpty()) {
    		RowFilter<TfidfBigramModel, Object> filterFrom = RowFilter.numberFilter(ComparisonType.AFTER, Double.parseDouble(from.getText()), col);
    		filters.add(filterFrom);
    	}
    	if (!to.getText().isEmpty()) {
    		RowFilter<TfidfBigramModel, Object> filterTo = RowFilter.numberFilter(ComparisonType.BEFORE, Double.parseDouble(to.getText()), col);
    		filters.add(filterTo);
    	}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField document;
    private javax.swing.JButton filterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfidfFrom;
    private javax.swing.JTextField tfidfTo;
    private javax.swing.JTextField word1;
    private javax.swing.JTextField word2;
    // End of variables declaration//GEN-END:variables
}
