package view;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.RowFilter.ComparisonType;
import javax.swing.table.TableRowSorter;

import model.TfidfModel;

public class TfidfFilterPane extends javax.swing.JPanel {
	
	private final TfidfModel model;
	private final JTable table;

    /**
     * Creates new form TfidfFilterPane
     */
	public TfidfFilterPane(JTable table) {
        initComponents();
        this.table = table;
        this.model = (TfidfModel) table.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        word = new javax.swing.JTextField();
        document = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfidfFrom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfidfTo = new javax.swing.JTextField();
        filterButton = new javax.swing.JButton();

        jLabel1.setText("Słowo");

        jLabel2.setText("Dokument");

        jLabel3.setText("Tf-idf");

        jLabel4.setText("od");

        jLabel5.setText("do");

        filterButton.setText("Filtruj");
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(word))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(document)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfidfFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfidfTo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 160, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(filterButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(word, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(document, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(tfidfFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfidfTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(filterButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
    	TableRowSorter<TfidfModel> sorter = new TableRowSorter<TfidfModel>(model);
    	table.setRowSorter(sorter);
    	
    	List<RowFilter<TfidfModel,Object>> filters = new ArrayList<RowFilter<TfidfModel,Object>>();
    	RowFilter<TfidfModel, Object> wordFilter = null;
    	RowFilter<TfidfModel, Object> docFilter = null;
    	
    	addFromToDoubleFilter(tfidfFrom, tfidfTo, filters, 2);
    	
    	RowFilter<TfidfModel, Object> compoundRowFilter = null;
    	
        //If current expression doesn't parse, don't update.
        try {
            wordFilter = RowFilter.regexFilter(word.getText(), 0);
            docFilter = RowFilter.regexFilter(document.getText(), 1);
            filters.add(wordFilter);
            filters.add(docFilter);
            compoundRowFilter = RowFilter.andFilter(filters);
        } catch (java.util.regex.PatternSyntaxException e) {
            return;
        }
        
        sorter.setRowFilter(compoundRowFilter);

    }//GEN-LAST:event_filterButtonActionPerformed
    
    private void addFromToDoubleFilter(JTextField from, JTextField to, 
    		List<RowFilter<TfidfModel,Object>> filters, int col) {
    	if (!from.getText().isEmpty()) {
    		RowFilter<TfidfModel, Object> filterFrom = RowFilter.numberFilter(ComparisonType.AFTER, Double.parseDouble(from.getText()), col);
    		filters.add(filterFrom);
    	}
    	if (!to.getText().isEmpty()) {
    		RowFilter<TfidfModel, Object> filterTo = RowFilter.numberFilter(ComparisonType.BEFORE, Double.parseDouble(to.getText()), col);
    		filters.add(filterTo);
    	}
    }

    public javax.swing.JButton getFilterButton() {
		return filterButton;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField document;
    private javax.swing.JButton filterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfidfFrom;
    private javax.swing.JTextField tfidfTo;
    private javax.swing.JTextField word;
    // End of variables declaration//GEN-END:variables
}
